// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufffarkyqwxdychqolcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZmZhcmt5cXd4ZHljaHFvbGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2MDEyMjksImV4cCI6MjA3MDE3NzIyOX0.EqwYFmcqpF85vfa2X_yc9FBCGXUSNsTAo7TyE2H4Gyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});